In [3]:
import numpy as np

In [4]:
?np.mean()

In [5]:
a=np.zeros(3)
print(a)

[ 0.  0.  0.]


In [7]:
a=np.arange(0,18,2)
print(a)

[ 0  2  4  6  8 10 12 14 16]


In [9]:
#3 random numbers between 1 and 100
a=np.random.randint(1,100,3)
print(a)

[63 91 12]


In [10]:
#first ten numbers squared
a=np.arange(10)**2
print(a)

[ 0  1  4  9 16 25 36 49 64 81]


In [11]:
#2 rows by 3 columns
a=np.ones( (2,3))
print(a)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [13]:
a=np.array(["pencil", "pen", "marker", "eraser"])
print(a)

['pencil' 'pen' 'marker' 'eraser']


In [20]:
a=np.arange(10)**2
c= max(a)
print(c)

81


In [28]:
a=np.linspace(0,100,10)
print(a)


[   0.           11.11111111   22.22222222   33.33333333   44.44444444
   55.55555556   66.66666667   77.77777778   88.88888889  100.        ]


In [34]:
Z=np.random.randint(0,100,30)
print(Z)
mean=np.mean(Z)
print(mean)

[69 81 72 55 57 86 29 77 61 94 73 59  3 14 63 70 77 64 19 52 45 94 30 22 29
  2 42 43  3 60]
51.5


In [38]:
subd=np.linspace(-1.3,2.5,64)
print(subd)
"""inv=np.linalg.inv(subd)
print(inv)"""
rev=subd[::-1]
print(rev)


[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]
[ 2.5         2.43968254  2.37936508  2.31904762  2.25873016  2.1984127
  2.13809524  2.07777778  2.01746032  1.95714286  1.8968254   1.83650794
  1.77619048  1.71587302  1.65555556  1.5952381   1.53492063  1.47460317
  1.

In [ ]:
#A way of coming with the same random sample
np.random.seed()